### ISSUE TITLE
Server crash unknown event

### ISSUE THREAD

**Issue by simon-kyger** [simon-kyger/brawlhallacrewbattles#11]
2018-02-21T05:33:52.961476+00:00 app[web.1]: /app/app.js:116
2018-02-21T05:33:52.961499+00:00 app[web.1]:                    sessions[game.inbound[i]].emit('loginsuccess', {username: game.inbound[i]});
2018-02-21T05:33:52.961502+00:00 app[web.1]:                                              ^
2018-02-21T05:33:52.961504+00:00 app[web.1]:
2018-02-21T05:33:52.961508+00:00 app[web.1]: TypeError: Cannot read property 'emit' of undefined
2018-02-21T05:33:52.961511+00:00 app[web.1]:     at leavegame (/app/app.js:116:30)
2018-02-21T05:33:52.961512+00:00 app[web.1]:     at Socket.socket.on (/app/app.js:40:30)
2018-02-21T05:33:52.961514+00:00 app[web.1]:     at Socket.emit (events.js:159:13)
2018-02-21T05:33:52.961516+00:00 app[web.1]:     at /app/node_modules/socket.io/lib/socket.js:513:12
2018-02-21T05:33:52.961518+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-02-21T05:33:52.961519+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by simon-kyger** [comment]
This may be a result of updating the server and not flushing all the sockets?  I have no idea, but I did notice that a users name was literally just "null" which makes no sense at all.

**Comment by simon-kyger** [comment]
v1.1.9 is hopefully going to fix this.

**Comment by simon-kyger** [comment]
Marking this as fixed, as it has not occurred after much beta usage of the app.
